version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    networks:
      - postgres
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: pastry-warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

